//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_Form.ToDoServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfXElement", Namespace="http://tempuri.org/", ItemName="XElement")]
    [System.SerializableAttribute()]
    public class ArrayOfXElement : System.Collections.Generic.List<System.Xml.Linq.XElement> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ToDoServiceReference.IToDoService")]
    public interface IToDoService {
        
        // CODEGEN: Generating message contract since element name getAllToDosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoService/getAllToDos", ReplyAction="http://tempuri.org/IToDoService/getAllToDosResponse")]
        Windows_Form.ToDoServiceReference.getAllToDosResponse getAllToDos(Windows_Form.ToDoServiceReference.getAllToDosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoService/getAllToDos", ReplyAction="http://tempuri.org/IToDoService/getAllToDosResponse")]
        System.Threading.Tasks.Task<Windows_Form.ToDoServiceReference.getAllToDosResponse> getAllToDosAsync(Windows_Form.ToDoServiceReference.getAllToDosRequest request);
        
        // CODEGEN: Generating message contract since element name getByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoService/getById", ReplyAction="http://tempuri.org/IToDoService/getByIdResponse")]
        Windows_Form.ToDoServiceReference.getByIdResponse getById(Windows_Form.ToDoServiceReference.getByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoService/getById", ReplyAction="http://tempuri.org/IToDoService/getByIdResponse")]
        System.Threading.Tasks.Task<Windows_Form.ToDoServiceReference.getByIdResponse> getByIdAsync(Windows_Form.ToDoServiceReference.getByIdRequest request);
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoService/saveTask", ReplyAction="http://tempuri.org/IToDoService/saveTaskResponse")]
        Windows_Form.ToDoServiceReference.saveTaskResponse saveTask(Windows_Form.ToDoServiceReference.saveTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoService/saveTask", ReplyAction="http://tempuri.org/IToDoService/saveTaskResponse")]
        System.Threading.Tasks.Task<Windows_Form.ToDoServiceReference.saveTaskResponse> saveTaskAsync(Windows_Form.ToDoServiceReference.saveTaskRequest request);
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoService/addToDo", ReplyAction="http://tempuri.org/IToDoService/addToDoResponse")]
        Windows_Form.ToDoServiceReference.addToDoResponse addToDo(Windows_Form.ToDoServiceReference.addToDoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoService/addToDo", ReplyAction="http://tempuri.org/IToDoService/addToDoResponse")]
        System.Threading.Tasks.Task<Windows_Form.ToDoServiceReference.addToDoResponse> addToDoAsync(Windows_Form.ToDoServiceReference.addToDoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoService/deleteToDo", ReplyAction="http://tempuri.org/IToDoService/deleteToDoResponse")]
        void deleteToDo(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoService/deleteToDo", ReplyAction="http://tempuri.org/IToDoService/deleteToDoResponse")]
        System.Threading.Tasks.Task deleteToDoAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoService/deleteAll", ReplyAction="http://tempuri.org/IToDoService/deleteAllResponse")]
        void deleteAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IToDoService/deleteAll", ReplyAction="http://tempuri.org/IToDoService/deleteAllResponse")]
        System.Threading.Tasks.Task deleteAllAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllToDosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllToDos", Namespace="http://tempuri.org/", Order=0)]
        public Windows_Form.ToDoServiceReference.getAllToDosRequestBody Body;
        
        public getAllToDosRequest() {
        }
        
        public getAllToDosRequest(Windows_Form.ToDoServiceReference.getAllToDosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllToDosRequestBody {
        
        public getAllToDosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllToDosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllToDosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Windows_Form.ToDoServiceReference.getAllToDosResponseBody Body;
        
        public getAllToDosResponse() {
        }
        
        public getAllToDosResponse(Windows_Form.ToDoServiceReference.getAllToDosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllToDosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Windows_Form.ToDoServiceReference.ArrayOfXElement getAllToDosResult;
        
        public getAllToDosResponseBody() {
        }
        
        public getAllToDosResponseBody(Windows_Form.ToDoServiceReference.ArrayOfXElement getAllToDosResult) {
            this.getAllToDosResult = getAllToDosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getById", Namespace="http://tempuri.org/", Order=0)]
        public Windows_Form.ToDoServiceReference.getByIdRequestBody Body;
        
        public getByIdRequest() {
        }
        
        public getByIdRequest(Windows_Form.ToDoServiceReference.getByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid id;
        
        public getByIdRequestBody() {
        }
        
        public getByIdRequestBody(System.Guid id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Windows_Form.ToDoServiceReference.getByIdResponseBody Body;
        
        public getByIdResponse() {
        }
        
        public getByIdResponse(Windows_Form.ToDoServiceReference.getByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getByIdResult;
        
        public getByIdResponseBody() {
        }
        
        public getByIdResponseBody(System.Xml.Linq.XElement getByIdResult) {
            this.getByIdResult = getByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveTask", Namespace="http://tempuri.org/", Order=0)]
        public Windows_Form.ToDoServiceReference.saveTaskRequestBody Body;
        
        public saveTaskRequest() {
        }
        
        public saveTaskRequest(Windows_Form.ToDoServiceReference.saveTaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class saveTaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dueDate;
        
        public saveTaskRequestBody() {
        }
        
        public saveTaskRequestBody(System.Guid id, string title, string description, System.DateTime dueDate) {
            this.id = id;
            this.title = title;
            this.description = description;
            this.dueDate = dueDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveTaskResponse", Namespace="http://tempuri.org/", Order=0)]
        public Windows_Form.ToDoServiceReference.saveTaskResponseBody Body;
        
        public saveTaskResponse() {
        }
        
        public saveTaskResponse(Windows_Form.ToDoServiceReference.saveTaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class saveTaskResponseBody {
        
        public saveTaskResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addToDoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addToDo", Namespace="http://tempuri.org/", Order=0)]
        public Windows_Form.ToDoServiceReference.addToDoRequestBody Body;
        
        public addToDoRequest() {
        }
        
        public addToDoRequest(Windows_Form.ToDoServiceReference.addToDoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addToDoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime duedate;
        
        public addToDoRequestBody() {
        }
        
        public addToDoRequestBody(string title, string description, System.DateTime duedate) {
            this.title = title;
            this.description = description;
            this.duedate = duedate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addToDoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addToDoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Windows_Form.ToDoServiceReference.addToDoResponseBody Body;
        
        public addToDoResponse() {
        }
        
        public addToDoResponse(Windows_Form.ToDoServiceReference.addToDoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addToDoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid addToDoResult;
        
        public addToDoResponseBody() {
        }
        
        public addToDoResponseBody(System.Guid addToDoResult) {
            this.addToDoResult = addToDoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IToDoServiceChannel : Windows_Form.ToDoServiceReference.IToDoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ToDoServiceClient : System.ServiceModel.ClientBase<Windows_Form.ToDoServiceReference.IToDoService>, Windows_Form.ToDoServiceReference.IToDoService {
        
        public ToDoServiceClient() {
        }
        
        public ToDoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ToDoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ToDoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ToDoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Windows_Form.ToDoServiceReference.getAllToDosResponse Windows_Form.ToDoServiceReference.IToDoService.getAllToDos(Windows_Form.ToDoServiceReference.getAllToDosRequest request) {
            return base.Channel.getAllToDos(request);
        }
        
        public Windows_Form.ToDoServiceReference.ArrayOfXElement getAllToDos() {
            Windows_Form.ToDoServiceReference.getAllToDosRequest inValue = new Windows_Form.ToDoServiceReference.getAllToDosRequest();
            inValue.Body = new Windows_Form.ToDoServiceReference.getAllToDosRequestBody();
            Windows_Form.ToDoServiceReference.getAllToDosResponse retVal = ((Windows_Form.ToDoServiceReference.IToDoService)(this)).getAllToDos(inValue);
            return retVal.Body.getAllToDosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Windows_Form.ToDoServiceReference.getAllToDosResponse> Windows_Form.ToDoServiceReference.IToDoService.getAllToDosAsync(Windows_Form.ToDoServiceReference.getAllToDosRequest request) {
            return base.Channel.getAllToDosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Windows_Form.ToDoServiceReference.getAllToDosResponse> getAllToDosAsync() {
            Windows_Form.ToDoServiceReference.getAllToDosRequest inValue = new Windows_Form.ToDoServiceReference.getAllToDosRequest();
            inValue.Body = new Windows_Form.ToDoServiceReference.getAllToDosRequestBody();
            return ((Windows_Form.ToDoServiceReference.IToDoService)(this)).getAllToDosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Windows_Form.ToDoServiceReference.getByIdResponse Windows_Form.ToDoServiceReference.IToDoService.getById(Windows_Form.ToDoServiceReference.getByIdRequest request) {
            return base.Channel.getById(request);
        }
        
        public System.Xml.Linq.XElement getById(System.Guid id) {
            Windows_Form.ToDoServiceReference.getByIdRequest inValue = new Windows_Form.ToDoServiceReference.getByIdRequest();
            inValue.Body = new Windows_Form.ToDoServiceReference.getByIdRequestBody();
            inValue.Body.id = id;
            Windows_Form.ToDoServiceReference.getByIdResponse retVal = ((Windows_Form.ToDoServiceReference.IToDoService)(this)).getById(inValue);
            return retVal.Body.getByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Windows_Form.ToDoServiceReference.getByIdResponse> Windows_Form.ToDoServiceReference.IToDoService.getByIdAsync(Windows_Form.ToDoServiceReference.getByIdRequest request) {
            return base.Channel.getByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Windows_Form.ToDoServiceReference.getByIdResponse> getByIdAsync(System.Guid id) {
            Windows_Form.ToDoServiceReference.getByIdRequest inValue = new Windows_Form.ToDoServiceReference.getByIdRequest();
            inValue.Body = new Windows_Form.ToDoServiceReference.getByIdRequestBody();
            inValue.Body.id = id;
            return ((Windows_Form.ToDoServiceReference.IToDoService)(this)).getByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Windows_Form.ToDoServiceReference.saveTaskResponse Windows_Form.ToDoServiceReference.IToDoService.saveTask(Windows_Form.ToDoServiceReference.saveTaskRequest request) {
            return base.Channel.saveTask(request);
        }
        
        public void saveTask(System.Guid id, string title, string description, System.DateTime dueDate) {
            Windows_Form.ToDoServiceReference.saveTaskRequest inValue = new Windows_Form.ToDoServiceReference.saveTaskRequest();
            inValue.Body = new Windows_Form.ToDoServiceReference.saveTaskRequestBody();
            inValue.Body.id = id;
            inValue.Body.title = title;
            inValue.Body.description = description;
            inValue.Body.dueDate = dueDate;
            Windows_Form.ToDoServiceReference.saveTaskResponse retVal = ((Windows_Form.ToDoServiceReference.IToDoService)(this)).saveTask(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Windows_Form.ToDoServiceReference.saveTaskResponse> Windows_Form.ToDoServiceReference.IToDoService.saveTaskAsync(Windows_Form.ToDoServiceReference.saveTaskRequest request) {
            return base.Channel.saveTaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<Windows_Form.ToDoServiceReference.saveTaskResponse> saveTaskAsync(System.Guid id, string title, string description, System.DateTime dueDate) {
            Windows_Form.ToDoServiceReference.saveTaskRequest inValue = new Windows_Form.ToDoServiceReference.saveTaskRequest();
            inValue.Body = new Windows_Form.ToDoServiceReference.saveTaskRequestBody();
            inValue.Body.id = id;
            inValue.Body.title = title;
            inValue.Body.description = description;
            inValue.Body.dueDate = dueDate;
            return ((Windows_Form.ToDoServiceReference.IToDoService)(this)).saveTaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Windows_Form.ToDoServiceReference.addToDoResponse Windows_Form.ToDoServiceReference.IToDoService.addToDo(Windows_Form.ToDoServiceReference.addToDoRequest request) {
            return base.Channel.addToDo(request);
        }
        
        public System.Guid addToDo(string title, string description, System.DateTime duedate) {
            Windows_Form.ToDoServiceReference.addToDoRequest inValue = new Windows_Form.ToDoServiceReference.addToDoRequest();
            inValue.Body = new Windows_Form.ToDoServiceReference.addToDoRequestBody();
            inValue.Body.title = title;
            inValue.Body.description = description;
            inValue.Body.duedate = duedate;
            Windows_Form.ToDoServiceReference.addToDoResponse retVal = ((Windows_Form.ToDoServiceReference.IToDoService)(this)).addToDo(inValue);
            return retVal.Body.addToDoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Windows_Form.ToDoServiceReference.addToDoResponse> Windows_Form.ToDoServiceReference.IToDoService.addToDoAsync(Windows_Form.ToDoServiceReference.addToDoRequest request) {
            return base.Channel.addToDoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Windows_Form.ToDoServiceReference.addToDoResponse> addToDoAsync(string title, string description, System.DateTime duedate) {
            Windows_Form.ToDoServiceReference.addToDoRequest inValue = new Windows_Form.ToDoServiceReference.addToDoRequest();
            inValue.Body = new Windows_Form.ToDoServiceReference.addToDoRequestBody();
            inValue.Body.title = title;
            inValue.Body.description = description;
            inValue.Body.duedate = duedate;
            return ((Windows_Form.ToDoServiceReference.IToDoService)(this)).addToDoAsync(inValue);
        }
        
        public void deleteToDo(System.Guid id) {
            base.Channel.deleteToDo(id);
        }
        
        public System.Threading.Tasks.Task deleteToDoAsync(System.Guid id) {
            return base.Channel.deleteToDoAsync(id);
        }
        
        public void deleteAll() {
            base.Channel.deleteAll();
        }
        
        public System.Threading.Tasks.Task deleteAllAsync() {
            return base.Channel.deleteAllAsync();
        }
    }
}
